### PR TITLE
Add Spigot 1.9 R1

### PR DESCRIPTION
**Pull request by notkaip**
I've had difficulties building, due to being unable to get a lot of the old CraftBukkit versions, but the API for Spigot shouldn't have changed much, so it should just be a simple matter of changing the package for NMS classes.

### CODE REVIEW

**Comment by evertiro** [comment]
It didn't change much, but it did change. I ran a successful build last night, but had to do a few patches first.

**Comment by notkaip** [comment]
@ghost1227 What did you do to make it build? Did you remove the versions that you can no longer get the artifacts for, or something else?

**Comment by evertiro** [comment]
Removed the older versions. I don't have a use for them myself, and wasn't planning on doing a PR until I've tested WE completely on 1.9. As of now, with my patched adapter, the only thing that appears broken is item frames and paintings (again).

**Comment by evertiro** [comment]
Spent half the day trying to track that bug down...

**Comment by evertiro** [comment]
@parryjacob semi-functional build https://github.com/sk89q/WorldEdit-Adapters/pull/4

**Comment by wizjany** [comment]
note that you don't need to build the whole thing every time, you can just run gradle project-name:task-name (eg `./gradlew spigot_v1_9_r1:build`)

**Pull request closed without merging**
