### PR TITLE
First pass, 1.9

### PR DESCRIPTION
**Pull request by evertiro**
This is a potentially nonfunctional update for 1.9. Not sure why pre-1.9 builds are no longer available, but since the CraftBukkit/Spigot builds are no longer available, I've removed the old projects. Provided adapter code for 1.9 works, but some entities don't copy correctly. As far as I've noticed, copy/paste is the only thing that bugs out at all, but please let me know if you find something else!

**Not Working**
- C/P Item Frames
- C/P Pictures
- C/P Minecarts

### CODE REVIEW

**Comment by evertiro** [comment]
I wasn't planning on submitting a PR until I figured out where I screwed up with the entity copy issue (or if it's in WE core), but since someone else submitted one that WON'T work, I thought I'd post this so others can hack at it and tell me what I did wrong!

**Comment by wizjany** [comment]
see my comment on #3, there is no reason to remove the old adapters just because you don't have the files to build them. also have you even tested those three things in 1.8? i've heard various reports that they don't even work there, and i'm pretty sure the adapter doesn't change that.

**Comment by evertiro** [comment]
Oooh neat trick! I didn't know that. I have tested those three things in 1.8. Pictures and minecarts work fine. Item frames occasionally fall, but not always. In 1.9, none of them copy at all... they just disappear.

**Comment by evertiro** [comment]
@wizjany Now that the official 1.9 adapter is out, can you tell me how far off I was, just for my personal reference?

**Comment by wizjany** [comment]
off of what? I stopped reading once i saw that you deleted all the old files.

**Comment by evertiro** [comment]
Never used gradle before, learning curve. My question was, is the adapter code I posted close to accurate. Save for the entity bug, it seemed to work fine, but I've never looked into the WE codebase before so trying to learn as I go. I do have experience with other Bukkit (and client) plugins, so not new to java, but new to WE. Basically, just want to know if I was on the right track. I suppose if/when the Adapters repo gets updated with the 1.9 adapter code I can just check myself though. Thanks!

**Comment by wizjany** [comment]
Well it's not like there are many changes, it's just copy paste from the old one plus a few renames when applicable. Also I'm still not sure about the entity bug, because everything outside of items frames etc works fine.

**Pull request closed without merging**
